### ISSUE TITLE
Criteria 3: HTML Elements and Content (4/4)

### ISSUE THREAD

**Issue by jlag34** [Akotar/Dasmoto-s-Arts-Crafts#3]
Awesome job in your HTML. Your page was clear and concise. Great job using a variety of different elements. Nice job using alt tags on all of your images. Only thing that I saw that was missing was wrapping section/div elements. Other than that, it looks good!

**Comment by Akotar** [comment]
Wrapped with div's. Will wrap them with div's in future projects ty.
