### ISSUE TITLE
Criteria 4: CSS Selectors and Syntax (3/4)

### ISSUE THREAD

**Issue by jlag34** [Akotar/Dasmoto-s-Arts-Crafts#4]
Your CSS looks good. Nice job adding styles to your headers and avoiding unnecessary classes. Lastly, nice job adding all of the necessary styles. The two things you missed in this file is to set your `font-family` on `html` or `body` so that you only have to set it once and all of the children elements will inherit that style. Also, you need to wrap the url on line 2 with quotes.

**Comment by Akotar** [comment]
On the example h3 and p wasn't Helvetica so I've decided not to make whole body Helvetica instead wrote it on specific ones to match up. For the url quote ty a lot 👍
